(()=>{
'use strict';
const $=(s,r=document)=>r.querySelector(s);
let canvas,ctx,W=900,H=520,dpr=1,yaw=-0.6,pitch=0.35,zoom=1,t=0,last=0,lastDraw=0,drag=false,px=0,py=0;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const sim=()=>$('#simTabs .sim-tab.active')?.dataset.sim||'progressive';
const v=(k,f)=>{const e=$(`#simControls [data-sim-control='${k}']`);const n=Number(e?.value);return Number.isFinite(n)?n:f;};
function rot([X,Y,Z]){const cy=Math.cos(yaw),sy=Math.sin(yaw),x1=X*cy+Z*sy,z1=-X*sy+Z*cy,cp=Math.cos(pitch),sp=Math.sin(pitch);return[x1,Y*cp-z1*sp,Y*sp+z1*cp]}
function P(p){const [X,Y,Z]=rot(p),s=Math.min(W,H)*zoom/Math.max(3.7,8+Z);return{x:W/2+X*s,y:H/2-Y*s,s}}
function line(a,b,c='#67c7ff',lw=2,al=1,dash=[]){const A=P(a),B=P(b);ctx.save();ctx.globalAlpha=al;ctx.strokeStyle=c;ctx.lineWidth=lw;ctx.setLineDash(dash);ctx.beginPath();ctx.moveTo(A.x,A.y);ctx.lineTo(B.x,B.y);ctx.stroke();ctx.restore()}
function path(ps,c='#67c7ff',lw=2,al=1){if(ps.length<2)return;ctx.save();ctx.globalAlpha=al;ctx.strokeStyle=c;ctx.lineWidth=lw;ctx.beginPath();let q=P(ps[0]);ctx.moveTo(q.x,q.y);for(let i=1;i<ps.length;i++){q=P(ps[i]);ctx.lineTo(q.x,q.y)}ctx.stroke();ctx.restore()}
function dot(p,r=5,c='#ffd56a',lab=''){const q=P(p);ctx.save();ctx.fillStyle=c;ctx.beginPath();ctx.arc(q.x,q.y,Math.max(2,r*q.s/70),0,Math.PI*2);ctx.fill();if(lab){ctx.fillStyle='#eaf6ff';ctx.font='700 11px system-ui';ctx.fillText(lab,q.x+7,q.y-7)}ctx.restore()}
function poly(ps,fill='rgba(103,199,255,.07)',stroke='rgba(103,199,255,.35)'){const q=ps.map(P);ctx.save();ctx.fillStyle=fill;ctx.strokeStyle=stroke;ctx.beginPath();q.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();ctx.fill();ctx.stroke();ctx.restore()}
function ring(cx,cz,r,y=0,c='#67c7ff',al=.2,a0=0,a1=Math.PI*2){const ps=[];for(let a=a0;a<=a1+.001;a+=(a1-a0)/42)ps.push([cx+r*Math.cos(a),y,cz+r*Math.sin(a)]);path(ps,c,1.2,al)}
function yRing(X,r){const ps=[];for(let a=0;a<=Math.PI*2+.01;a+=Math.PI/28)ps.push([X,r*Math.cos(a),r*Math.sin(a)]);path(ps,'#477995',1,.35)}
function label(s,p,c='#dff5ff'){const q=P(p);ctx.fillStyle=c;ctx.font='700 11px system-ui';ctx.fillText(s,q.x+6,q.y-5)}
function grid(){for(let i=-3;i<=3;i+=.6){line([-3,-1.75,i],[3,-1.75,i],'#27445e',.7,.3);line([i,-1.75,-3],[i,-1.75,3],'#27445e',.7,.3)}}
function clear(){ctx.setTransform(dpr,0,0,dpr,0,0);const g=ctx.createRadialGradient(W*.5,H*.35,20,W*.5,H*.5,Math.max(W,H)*.75);g.addColorStop(0,'#153b60');g.addColorStop(1,'#06111d');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);grid()}
function info(title,text){const e=$('#sim3DInfoV17');if(e)e.innerHTML=`<strong>${title}</strong> · ${text}`}
function progressive(){const A=.45+v('A',70)/130,L=clamp(v('lambda',220)/115,.8,3.2),ph=t*v('f',1.2)*2.4;for(const z of[-.7,0,.7]){const ps=[];for(let X=-3;X<=3;X+=.06)ps.push([X,A*Math.sin(X/L*Math.PI*2-ph),z]);path(ps,z===0?'#67c7ff':'#8bbde0',z===0?3:1.2,z===0?1:.4)}for(let i=0;i<=12;i++){const X=-3+i*.5;dot([X,A*Math.sin(X/L*Math.PI*2-ph),0],4)}line([-2.6,1.55,-1],[2.4,1.55,-1],'#63d9a4',3,.85);label('energy / phase →',[0,1.55,-1],'#9cf0ca');info('Progressive wave in 3D','Particles oscillate locally while phase and energy propagate along the wave.')}
function polarisation(){const tr=v('mode',0)<.5,ang=v('angle',35)*Math.PI/180,ph=t*2.5;if(tr){const ps=[];for(let X=-3;X<=3;X+=.06)ps.push([X,.8*Math.sin(X*3-ph),0]);path(ps,'#67c7ff',3);for(let X=-2.7;X<=2.7;X+=.45){const E=.68*Math.sin(X*3-ph);line([X,0,0],[X,E,0],'#ffd56a',1.2,.65)}}else{for(let i=0;i<28;i++){const X=-3+i*6/27;dot([X+.16*Math.sin(X*5-ph),0,0],4,'#67c7ff')}}const X=1.35,R=1.2,u=[0,Math.cos(ang)*R,Math.sin(ang)*R],q=[0,-Math.sin(ang)*R,Math.cos(ang)*R];poly([[X,u[1]+q[1],u[2]+q[2]],[X,u[1]-q[1],u[2]-q[2]],[X,-u[1]-q[1],-u[2]-q[2]],[X,-u[1]+q[1],-u[2]+q[2]]],'rgba(255,213,106,.06)','rgba(255,213,106,.65)');line([X,-u[1],-u[2]],[X,u[1],u[2]],'#ffd56a',4);info('Polarisation in 3D',tr?'The analyser orientation selects a component of a transverse oscillation.':'Longitudinal displacement is parallel to propagation, so there is no transverse plane to select.')}
function standing(){const n=Math.round(v('n',2)),A=.35+v('A',80)/150,ph=Math.cos(t*3),ps=[];for(let X=-3;X<=3;X+=.04)ps.push([X,A*Math.sin(n*Math.PI*(X+3)/6)*ph,0]);path(ps,'#67c7ff',3);for(let i=0;i<=n;i++){const X=-3+6*i/n;dot([X,0,0],5,'#ffbd66',i===0||i===n?'fixed':'node')}info('Stationary wave in 3D',`The pattern contains ${n} half-wavelength section${n===1?'':'s'}; the node positions stay fixed.`)}
function interference(){const L=clamp(v('lambda',70)/60,.55,2),sep=clamp(v('sep',180)/105,.7,2.6),a=[-1.8,0,-sep/2],b=[-1.8,0,sep/2];dot(a,7,'#63d9a4','S₁');dot(b,7,'#9a86ff','S₂');for(const s of[a,b])for(let j=1;j<=5;j++)ring(s[0],s[2],((t+j*L)%5.2)+.1,0,s===a?'#63d9a4':'#9a86ff',.16);const q=[-.5+v('px',.72)*4,.05,(v('py',.52)-.5)*5];dot(q,7,'#ffd56a','detector');line(a,q,'#63d9a4',1,.5,[5,4]);line(b,q,'#9a86ff',1,.5,[5,4]);info('Interference field in 3D','The detector receives two paths. Moving it changes path difference and therefore phase difference.')}
function doubleSlit(){const sep=clamp(v('sMm',.35)*3,.5,2),D=v('D',2),lam=v('lambdaNm',600),bx=-1.5,sx=2.7;poly([[bx,-1.7,-2],[bx,1.7,-2],[bx,1.7,2],[bx,-1.7,2]],'rgba(120,145,165,.12)','rgba(160,180,198,.42)');const a=[bx,0,-sep/2],b=[bx,0,sep/2];dot(a,5,'#63d9a4','slit');dot(b,5,'#63d9a4','slit');poly([[sx,-1.7,-2.1],[sx,1.7,-2.1],[sx,1.7,2.1],[sx,-1.7,2.1]],'rgba(180,220,255,.04)','rgba(180,220,255,.35)');const sp=clamp((lam/600)*(D/2)/Math.max(.15,v('sMm',.35))*.33,.16,.72);for(let k=-5;k<=5;k++){const z=k*sp;if(Math.abs(z)>2)continue;line([sx,-1.2,z],[sx,1.2,z],k===0?'#fff4bd':'#67c7ff',k===0?5:3,Math.max(.2,1-Math.abs(k)*.12));line(a,[sx,0,z],'#63d9a4',.8,.14);line(b,[sx,0,z],'#9a86ff',.8,.14)}info('Young double slit in 3D','The two paths to each screen position make the changing path difference and fringe spacing visible.')}
function diffraction(){const a=clamp(v('slitUm',40)/30,.35,2.5),lam=v('lambdaNm',600),bx=-1.3;poly([[bx,-1.8,-2],[bx,1.8,-2],[bx,1.8,-a/2],[bx,-1.8,-a/2]],'rgba(120,145,165,.14)','rgba(160,180,198,.4)');poly([[bx,-1.8,a/2],[bx,1.8,a/2],[bx,1.8,2],[bx,-1.8,2]],'rgba(120,145,165,.14)','rgba(160,180,198,.4)');const spread=clamp((lam/600)/(a/1.3)*.9,.25,1.35);for(let k=-6;k<=6;k++){const th=k/6*spread;line([bx,0,0],[3,0,Math.tan(th)*(3-bx)],k===0?'#dff5ff':'#67c7ff',k===0?2.5:1.2,Math.max(.12,1-Math.abs(k)*.1))}info('Single-slit diffraction in 3D','The outgoing angular spread grows when wavelength increases or slit width decreases.')}
function grating(){const N=v('linesMm',500)*1e3,lam=v('lambdaNm',600)*1e-9,d=1/N,bx=-1.4,max=Math.min(5,Math.floor(d/lam+1e-9));poly([[bx,-1.8,-2],[bx,1.8,-2],[bx,1.8,2],[bx,-1.8,2]],'rgba(120,145,165,.09)','rgba(160,180,198,.4)');for(let z=-1.7;z<=1.7;z+=.22)line([bx,-1.5,z],[bx,1.5,z],'#aabbd1',.7,.5);for(let n=-max;n<=max;n++){const s=n*lam/d;if(Math.abs(s)>1)continue;const th=Math.asin(s),z=Math.tan(th)*4.1;line([bx,0,0],[2.7,0,z],n===0?'#f1f7ff':'#67c7ff',n===0?2.4:2,.82);label(`n=${n}`,[2.45,.08,z])}info('Diffraction grating in 3D',`Principal maxima leave at discrete angles; with these settings the largest displayed order is |n|=${max}.`)}
function refraction(){const n1=v('n1',1.5),n2=v('n2',1),a=v('theta',30)*Math.PI/180,s=n1*Math.sin(a)/n2,tir=Math.abs(s)>1;poly([[-3,0,-3],[3,0,-3],[3,0,3],[-3,0,3]],'rgba(103,199,255,.055)','rgba(103,199,255,.25)');line([0,-2.2,0],[0,2.2,0],'#dfe9f1',1.2,.65,[5,4]);const L=2.8;line([-L*Math.sin(a),L*Math.cos(a),0],[0,0,0],'#ffd56a',3);if(tir){line([0,0,0],[L*Math.sin(a),L*Math.cos(a),0],'#ffb36a',3);label('TIR',[1.2,1.5,0],'#ffd56a')}else{const b=Math.asin(s);line([0,0,0],[L*Math.sin(b),-L*Math.cos(b),0],'#67c7ff',3);label('refracted',[1,-1.45,0],'#9fddff')}info('Refraction and TIR in 3D',tir?'The incidence angle is above the critical condition, so the ray remains in the original medium.':'The interface and normal are visible in depth; the refracted direction follows Snell’s law.')}
function fibre(){const len=v('length',1000),m=v('modal',3),spec=v('spectral',2),abs=v('absorption',.15),R=.72;for(let X=-3;X<=3;X+=.6)yRing(X,R);for(let a=0;a<Math.PI*2;a+=Math.PI/6)line([-3,R*Math.cos(a),R*Math.sin(a)],[3,R*Math.cos(a),R*Math.sin(a)],'#477995',.9,.32);const modes=Math.max(1,Math.min(5,Math.round(m/2)+1));for(let j=0;j<modes;j++){const ps=[],amp=.16+j*.09,f=1.1+j*.42;for(let X=-2.9;X<=2.9;X+=.06)ps.push([X,amp*Math.sin((X+3)*f*2+t*.8),amp*Math.cos((X+3)*f*2+t*.8)]);path(ps,j%2?'#9a86ff':'#67c7ff',1.5,.66)}const X=-2.8+5.6*((t*.55)%1),loss=Math.pow(10,-abs*(len/1000)/10);dot([X,0,0],7+spec*.4,`rgba(255,213,106,${clamp(.25+loss*.75,.25,1)})`,'pulse');info('Optical fibre in 3D',`The cylindrical core shows guided paths and a moving pulse over ${Math.round(len)} m. Modal spread changes path variety; material dispersion changes pulse spread; absorption reduces signal strength.`)}
function draw(){if(!ctx)return;clear();const f={progressive,polarisation,standing,interference,doubleSlit,diffraction,grating,refraction,fibre}[sim()]||progressive;f()}
function camera(k){if(k==='front'){yaw=0;pitch=0;zoom=1}else if(k==='top'){yaw=0;pitch=-1.2;zoom=.92}else if(k==='iso'){yaw=-.72;pitch=.5;zoom=1}else{yaw=-.6;pitch=.35;zoom=1}draw()}
function resize(){if(!canvas)return;const r=canvas.getBoundingClientRect();if(!r.width)return;dpr=Math.min(devicePixelRatio||1,1.6);W=r.width;H=r.height;canvas.width=Math.round(W*dpr);canvas.height=Math.round(H*dpr);ctx=canvas.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);draw()}
function setup(){const wrap=$('#view-lab .viewer-wrap'),old=$('#simCanvas');if(!wrap||!old||$('#simCanvas3DV17'))return;old.classList.add('legacy-sim-hidden-v15');wrap.classList.add('v15-3d-ready');canvas=document.createElement('canvas');canvas.id='simCanvas3DV17';canvas.className='waves-3d-v15';canvas.setAttribute('aria-label','Interactive rotatable 3D Waves simulation');wrap.insertBefore(canvas,wrap.firstChild);const help=document.createElement('div');help.className='sim-3d-help-v15';help.textContent='Drag to orbit · wheel to zoom · all physics controls remain live';wrap.appendChild(help);const badge=document.createElement('div');badge.className='sim-3d-badge-v15';badge.textContent='Interactive 3D';wrap.appendChild(badge);const bar=document.createElement('div');bar.className='sim-3d-toolbar-v15';bar.innerHTML='<button data-v17cam="reset">Reset view</button><button data-v17cam="front">Front</button><button data-v17cam="top">Top</button><button data-v17cam="iso">Isometric</button>';wrap.appendChild(bar);bar.querySelectorAll('[data-v17cam]').forEach(b=>b.onclick=()=>camera(b.dataset.v17cam));const note=document.createElement('div');note.id='sim3DInfoV17';note.className='three-d-explain-v15';wrap.parentElement?.appendChild(note);ctx=canvas.getContext('2d');canvas.addEventListener('pointerdown',e=>{drag=true;px=e.clientX;py=e.clientY;canvas.setPointerCapture?.(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-px,dy=e.clientY-py;px=e.clientX;py=e.clientY;yaw+=dx*.008;pitch=clamp(pitch+dy*.007,-1.25,1.25);draw()});canvas.addEventListener('pointerup',()=>drag=false);canvas.addEventListener('pointercancel',()=>drag=false);canvas.addEventListener('wheel',e=>{e.preventDefault();zoom=clamp(zoom*(e.deltaY>0?.92:1.08),.62,1.8);draw()},{passive:false});document.addEventListener('input',e=>{if(e.target.matches?.('#simControls [data-sim-control]'))requestAnimationFrame(draw)});document.addEventListener('click',e=>{if(e.target.closest?.('[data-sim],#resetSim,#slowMotion,#playPause'))setTimeout(draw,35)});window.addEventListener('resize',resize);resize();window.dispatchEvent(new Event('resize'));}
function loop(ts){requestAnimationFrame(loop);if(!$('#view-lab')?.classList.contains('active-view')||document.hidden)return;if(ts-lastDraw<33)return;const dt=last?Math.min(.06,(ts-last)/1000):0;last=ts;lastDraw=ts;if(!(($('#simState')?.textContent||'').toLowerCase().includes('paused')))t+=dt*($('#slowMotion')?.classList.contains('primary')?0.35:1);draw()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{setTimeout(setup,220);requestAnimationFrame(loop)});else{setTimeout(setup,220);requestAnimationFrame(loop)}
})();