(()=>{
"use strict";
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
let c,x,w=900,h=520,dpr=1,yaw=-.58,pitch=.34,zoom=1,t=0,last=0,drag=false,px=0,py=0,raf=0,lastDraw=0;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const val=(k,f)=>{const e=$(`#simControls [data-sim-control='${k}']`),n=Number(e?.value);return Number.isFinite(n)?n:f;};
const sim=()=>$("#simTabs .sim-tab.active")?.dataset.sim||"progressive";
const active=()=>$("#view-lab")?.classList.contains("active-view")&&!document.hidden;
const paused=()=>$("#simState")?.textContent?.toLowerCase().includes("paused");
function setup(){const wrap=$("#view-lab .viewer-wrap"),old=$("#simCanvas");if(!wrap||!old||$("#simCanvas3DV15"))return;old.classList.add("legacy-sim-hidden-v15");wrap.classList.add("v15-3d-ready");c=document.createElement("canvas");c.id="simCanvas3DV15";c.className="waves-3d-v15";c.setAttribute("aria-label","Interactive rotatable 3D Waves simulation");wrap.insertBefore(c,wrap.firstChild);const help=document.createElement("div");help.className="sim-3d-help-v15";help.textContent="Drag to orbit · pinch/wheel to zoom · controls still change the physics";wrap.appendChild(help);const badge=document.createElement("div");badge.className="sim-3d-badge-v15";badge.textContent="Interactive 3D";wrap.appendChild(badge);const bar=document.createElement("div");bar.className="sim-3d-toolbar-v15";bar.innerHTML='<button data-cam="reset">Reset view</button><button data-cam="front">Front</button><button data-cam="top">Top</button><button data-cam="iso">Isometric</button>';wrap.appendChild(bar);bar.querySelectorAll("[data-cam]").forEach(b=>b.onclick=()=>camera(b.dataset.cam));const note=document.createElement("div");note.className="three-d-explain-v15";note.id="sim3DExplainV15";wrap.parentElement?.appendChild(note);x=c.getContext("2d");bind();resize();window.dispatchEvent(new Event("resize"));draw();}
function bind(){c.addEventListener("pointerdown",e=>{drag=true;px=e.clientX;py=e.clientY;c.setPointerCapture?.(e.pointerId)});c.addEventListener("pointermove",e=>{if(!drag)return;const dx=e.clientX-px,dy=e.clientY-py;px=e.clientX;py=e.clientY;yaw+=dx*.008;pitch=clamp(pitch+dy*.007,-1.25,1.25);draw()});c.addEventListener("pointerup",()=>drag=false);c.addEventListener("pointercancel",()=>drag=false);c.addEventListener("wheel",e=>{e.preventDefault();zoom=clamp(zoom*(e.deltaY>0?.92:1.08),.62,1.8);draw()},{passive:false});c.addEventListener("dblclick",()=>camera("reset"));document.addEventListener("input",e=>{if(e.target.matches?.("#simControls [data-sim-control]"))requestAnimationFrame(draw)});document.addEventListener("click",e=>{if(e.target.closest?.("[data-sim],#resetSim,#slowMotion,#playPause"))setTimeout(draw,40)});window.addEventListener("resize",resize);}
function camera(k){if(k==="front"){yaw=0;pitch=0;zoom=1}else if(k==="top"){yaw=0;pitch=-1.22;zoom=.92}else if(k==="iso"){yaw=-.7;pitch=.5;zoom=1}else{yaw=-.58;pitch=.34;zoom=1}draw()}
function resize(){if(!c)return;const r=c.getBoundingClientRect();if(!r.width)return;dpr=Math.min(devicePixelRatio||1,1.65);w=r.width;h=r.height;c.width=Math.round(w*dpr);c.height=Math.round(h*dpr);x=c.getContext("2d");x.setTransform(dpr,0,0,dpr,0,0);draw()}
function rot(p){let [X,Y,Z]=p;const cy=Math.cos(yaw),sy=Math.sin(yaw);let x1=X*cy+Z*sy,z1=-X*sy+Z*cy;const cp=Math.cos(pitch),sp=Math.sin(pitch);let y1=Y*cp-z1*sp,z2=Y*sp+z1*cp;return [x1,y1,z2]}
function P(p){const [X,Y,Z]=rot(p),cam=8.2,den=cam+Z,sc=Math.min(w,h)*1.03*zoom/Math.max(3.5,den);return{x:w/2+X*sc,y:h/2-Y*sc,z:Z,s:sc}}
function line3(a,b,col="#67c7ff",lw=2,alpha=1,dash=[]){const A=P(a),B=P(b);x.save();x.globalAlpha=alpha;x.strokeStyle=col;x.lineWidth=lw;x.setLineDash(dash);x.beginPath();x.moveTo(A.x,A.y);x.lineTo(B.x,B.y);x.stroke();x.restore()}
function path3(points,col="#67c7ff",lw=2,alpha=1){if(points.length<2)return;x.save();x.globalAlpha=alpha;x.strokeStyle=col;x.lineWidth=lw;x.beginPath();const a=P(points[0]);x.moveTo(a.x,a.y);for(let i=1;i<points.length;i++){const q=P(points[i]);x.lineTo(q.x,q.y)}x.stroke();x.restore()}
function dot3(p,r=5,col="#ffd56a",label=""){const q=P(p);x.save();x.fillStyle=col;x.shadowColor=col;x.shadowBlur=7;x.beginPath();x.arc(q.x,q.y,Math.max(2,r*q.s/70),0,Math.PI*2);x.fill();x.shadowBlur=0;if(label){x.fillStyle="#dff5ff";x.font="700 11px system-ui";x.fillText(label,q.x+7,q.y-7)}x.restore()}
function poly3(points,fill="rgba(103,199,255,.08)",stroke="rgba(103,199,255,.35)"){const ps=points.map(P);x.save();x.fillStyle=fill;x.strokeStyle=stroke;x.lineWidth=1.2;x.beginPath();ps.forEach((q,i)=>i?x.lineTo(q.x,q.y):x.moveTo(q.x,q.y));x.closePath();x.fill();x.stroke();x.restore()}
function label3(txt,p,col="#dff5ff"){const q=P(p);x.fillStyle=col;x.font="700 11px system-ui";x.fillText(txt,q.x+6,q.y-5)}
function circlePlane(cx,cz,r,y=0,col="#67c7ff",alpha=.3,start=0,end=Math.PI*2){const pts=[];for(let a=start;a<=end+.001;a+=(end-start)/48)pts.push([cx+r*Math.cos(a),y,cz+r*Math.sin(a)]);path3(pts,col,1.3,alpha)}
function grid(){for(let i=-3;i<=3;i+=.5){line3([-3,-1.75,i],[3,-1.75,i],"#27445e",.7,.38);line3([i,-1.75,-3],[i,-1.75,3],"#27445e",.7,.38)}line3([-3,-1.75,0],[3,-1.75,0],"#496b88",1,.65);line3([0,-1.75,-3],[0,-1.75,3],"#496b88",1,.65)}
function clear(){x.setTransform(dpr,0,0,dpr,0,0);const g=x.createRadialGradient(w*.5,h*.35,20,w*.5,h*.5,Math.max(w,h)*.75);g.addColorStop(0,"#153b60");g.addColorStop(1,"#06111d");x.fillStyle=g;x.fillRect(0,0,w,h);grid()}
function progressive(){const A=.45+val("A",70)/130,lam=clamp(val("lambda",220)/115,.8,3.2),f=val("f",1.2),phase=t*f*2.4;for(const z of[-.75,0,.75]){const pts=[];for(let X=-3;X<=3.01;X+=.06)pts.push([X,A*Math.sin((X/lam)*Math.PI*2-phase),z]);path3(pts,z===0?"#67c7ff":"#8bbde0",z===0?3:1.3,z===0?1:.45)}for(let i=0;i<=12;i++){const X=-3+i*.5,Y=A*Math.sin((X/lam)*Math.PI*2-phase);dot3([X,Y,0],4,"#ffd56a")}line3([-2.7,1.6,-1],[2.5,1.6,-1],"#63d9a4",3,.85);label3("energy / phase →",[.2,1.6,-1],"#9cf0ca");explain("Progressive wave","The 3D view separates particle oscillation from the direction in which phase and energy propagate. Orbit the scene to see that the wave has spatial extent, while individual particles remain local.")}
function polarisation(){const transverse=val("mode",0)<.5,ang=val("angle",35)*Math.PI/180,phase=t*2.5;if(transverse){const pts=[];for(let X=-3;X<=3;X+=.06)pts.push([X,.8*Math.sin(X*3-phase),0]);path3(pts,"#67c7ff",3);for(let X=-2.7;X<=2.7;X+=.45){const E=.7*Math.sin(X*3-phase);line3([X,0,0],[X,E,0],"#ffd56a",1.4,.65)}}else{for(let i=0;i<28;i++){const base=-3+i*6/27,dx=.16*Math.sin(base*5-phase);dot3([base+dx,0,0],4,"#67c7ff")}}const X=1.35,R=1.35;const u=[0,Math.cos(ang)*R,Math.sin(ang)*R],v=[0,-Math.sin(ang)*R,Math.cos(ang)*R];poly3([[X,u[1]+v[1],u[2]+v[2]],[X,u[1]-v[1],u[2]-v[2]],[X,-u[1]-v[1],-u[2]-v[2]],[X,-u[1]+v[1],-u[2]+v[2]]],"rgba(255,213,106,.07)","rgba(255,213,106,.65)");line3([X,-u[1],-u[2]],[X,u[1],u[2]],"#ffd56a",4);label3("analyser",[X,1.55,0],"#ffd56a");explain("Polarisation in 3D",transverse?"The oscillation lies perpendicular to propagation. Rotate the analyser plane and compare its axis with the oscillation direction; this geometric selectivity is why polarisation is evidence for transverse waves.":"The particles oscillate along the propagation axis, showing a longitudinal wave. There is no independent transverse oscillation plane to select with a polariser.")}
function standing(){const n=Math.round(val("n",2)),A=.35+val("A",80)/150,phase=Math.cos(t*3),pts=[];for(let X=-3;X<=3;X+=.04)pts.push([X,A*Math.sin(n*Math.PI*(X+3)/6)*phase,0]);path3(pts,"#67c7ff",3);for(const z of[-.12,.12])path3(pts.map(p=>[p[0],p[1],z]),"#8bbde0",1,.35);for(let i=0;i<=n;i++){const X=-3+6*i/n;dot3([X,0,0],5,"#ffbd66",i===0||i===n?"fixed":"node")}explain("Stationary wave in 3D",`The string contains ${n} half-wavelength section${n===1?"":"s"}. Nodes remain fixed while antinode displacement oscillates. Orbiting makes it easier to see that the pattern is spatially fixed rather than travelling along the string.`)}
function interference(){const lam=clamp(val("lambda",70)/60,.55,2.0),sep=clamp(val("sep",180)/105,.7,2.6),s1=[-1.8,0,-sep/2],s2=[-1.8,0,sep/2];dot3(s1,7,"#63d9a4","S₁");dot3(s2,7,"#9a86ff","S₂");for(const s of[s1,s2])for(let j=1;j<=5;j++){const r=((t*1.1+j*lam)%5.3)+.1;circlePlane(s[0],s[2],r,0,s===s1?"#63d9a4":"#9a86ff",.18)}const qx=-.5+val("px",.72)*4,qz=(val("py",.52)-.5)*5;dot3([qx,.05,qz],7,"#ffd56a","detector");line3(s1,[qx,0,qz],"#63d9a4",1,.5,[5,4]);line3(s2,[qx,0,qz],"#9a86ff",1,.5,[5,4]);explain("Two-source interference field","The circular wavefronts expand from two coherent sources across the same 3D plane. The detector receives waves that have travelled different distances, so moving it changes path difference and therefore phase difference.")}
function doubleSlit(){const s=clamp(val("sMm",.35)*3.1,.5,2.1),D=val("D",2),lam=val("lambdaNm",600);const bx=-1.5,screen=2.7;poly3([[bx,-1.7,-2],[bx,1.7,-2],[bx,1.7,2],[bx,-1.7,2]],"rgba(120,145,165,.12)","rgba(160,180,198,.42)");const sl1=[bx,0,-s/2],sl2=[bx,0,s/2];dot3(sl1,5,"#63d9a4","slit");dot3(sl2,5,"#63d9a4","slit");poly3([[screen,-1.7,-2.15],[screen,1.7,-2.15],[screen,1.7,2.15],[screen,-1.7,2.15]],"rgba(180,220,255,.045)","rgba(180,220,255,.35)");const spacing=clamp((lam/600)*(D/2)/Math.max(.15,val("sMm",.35))*0.33,.16,.72);for(let k=-5;k<=5;k++){const z=k*spacing;if(Math.abs(z)>2)continue;line3([screen,-1.25,z],[screen,1.25,z],k===0?"#fff4bd":"#67c7ff",k===0?5:3,Math.max(.18,1-Math.abs(k)*.12));line3(sl1,[screen,0,z],"#63d9a4",.9,.16);line3(sl2,[screen,0,z],"#9a86ff",.9,.16)}label3("double slit",[bx,1.9,0]);label3("fringe screen",[screen,1.9,0]);explain("Young double slit in 3D","Two coherent slit sources illuminate a screen. The ray pairs make the changing path difference visible. Increase D or wavelength to separate fringes; increase slit separation to bring fringes closer together.")}
function diffraction(){const a=clamp(val("slitUm",40)/30,.35,2.6),lam=val("lambdaNm",600);const bx=-1.3;poly3([[bx,-1.8,-2],[bx,1.8,-2],[bx,1.8,-a/2],[bx,-1.8,-a/2]],"rgba(120,145,165,.14)","rgba(160,180,198,.4)");poly3([[bx,-1.8,a/2],[bx,1.8,a/2],[bx,1.8,2],[bx,-1.8,2]],"rgba(120,145,165,.14)","rgba(160,180,198,.4)");const spread=clamp((lam/600)/(a/1.3)*.9,.25,1.45);for(let k=-6;k<=6;k++){const th=(k/6)*spread;line3([bx,0,0],[3,0,Math.tan(th)*(3-bx)],k===0?"#dff5ff":"#67c7ff",k===0?2.6:1.3,Math.max(.12,1-Math.abs(k)*.1))}for(let r=.55;r<4.8;r+=.72)circlePlane(bx,0,r,0,"#67c7ff",.16,-spread,spread);explain("Single-slit diffraction in 3D","The aperture acts as a region from which the wave spreads. The fan angle increases when wavelength is larger or slit width is smaller, matching the qualitative λ/a dependence required for this topic.")}
function grating(){const N=val("linesMm",500)*1e3,lam=val("lambdaNm",600)*1e-9,d=1/N,bx=-1.4,max=Math.min(5,Math.floor(d/lam+1e-9));poly3([[bx,-1.8,-2],[bx,1.8,-2],[bx,1.8,2],[bx,-1.8,2]],"rgba(120,145,165,.09)","rgba(160,180,198,.4)");for(let z=-1.75;z<=1.75;z+=.22)line3([bx,-1.5,z],[bx,1.5,z],"#aabbd1",.75,.5);for(let n=-max;n<=max;n++){const s=n*lam/d;if(Math.abs(s)>1)continue;const th=Math.asin(s),z=Math.tan(th)*4.2;line3([bx,0,0],[2.8,0,z],n===0?"#f1f7ff":"#67c7ff",n===0?2.4:2,.82);label3(`n=${n}`,[2.55,.08,z],"#bceaff")}explain("Diffraction grating in 3D",`The grating sends principal maxima into discrete directions. With the current settings the largest displayed order is |n|=${max}. Orbit the view to see the angular separation of the order beams.`)}
function refraction(){const n1=val("n1",1.5),n2=val("n2",1),th1=val("theta",30)*Math.PI/180,s=n1*Math.sin(th1)/n2,tir=Math.abs(s)>1;poly3([[-3,0,-3],[3,0,-3],[3,0,3],[-3,0,3]],"rgba(103,199,255,.055)","rgba(103,199,255,.25)");for(let k=-3;k<=3;k+=.75){line3([-3,0,k],[3,0,k],"#294e69",.7,.4);line3([k,0,-3],[k,0,3],"#294e69",.7,.4)}line3([0,-2.2,0],[0,2.2,0],"#dfe9f1",1.2,.65,[5,4]);const L=2.8;const inc=[-L*Math.sin(th1),L*Math.cos(th1),0];line3(inc,[0,0,0],"#ffd56a",3);if(tir){const out=[L*Math.sin(th1),L*Math.cos(th1),0];line3([0,0,0],out,"#ffb36a",3);label3("TIR",[1.2,1.5,0],"#ffd56a")}else{const th2=Math.asin(s),out=[L*Math.sin(th2),-L*Math.cos(th2),0];line3([0,0,0],out,"#67c7ff",3);label3("refracted",[1.0,-1.45,0],"#9fddff")}label3("normal",[0,2.2,0]);explain("Refraction and TIR in 3D",tir?"The incidence angle is above the critical condition for this higher-to-lower refractive-index boundary, so no transmitted ray is drawn: the model shows total internal reflection.":"The interface is a 3D plane and the dashed line is the normal. The refracted direction follows Snell's law while frequency remains unchanged across the boundary.")}
function fibre(){const length=val("length",1000),modal=val("modal",3),spec=val("spectral",2),abs=val("absorption",.15),R=.72;for(let X=-3;X<=3.01;X+=.6)circleYZ(X,R,"#477995",.35);for(let a=0;a<Math.PI*2;a+=Math.PI/6)line3([-3,R*Math.cos(a),R*Math.sin(a)],[3,R*Math.cos(a),R*Math.sin(a)],"#477995",.9,.32);const modes=Math.max(1,Math.min(5,Math.round(modal/2)+1));for(let m=0;m<modes;m++){const pts=[],amp=.16+m*.09,freq=1.1+m*.42;for(let X=-2.9;X<=2.9;X+=.06)pts.push([X,amp*Math.sin((X+3)*freq*2+t*.8),amp*Math.cos((X+3)*freq*2+t*.8)]);path3(pts,m%2?"#9a86ff":"#67c7ff",1.5,.66)}const prog=((t*.55)%1),X=-2.8+5.6*prog,loss=Math.pow(10,-abs*(length/1000)/10);dot3([X,0,0],7+spec*.45,`rgba(255,213,106,${clamp(.25+loss*.75,.25,1)})`,"pulse");label3("higher-n core / lower-n cladding",[-1.5,1.02,0],"#bfe6ff");explain("Optical fibre in 3D",`Multiple guided paths are shown inside a cylindrical core. More path variety represents greater modal dispersion; spectral width contributes material dispersion; absorption reduces received signal strength. The current link length is ${Math.round(length)} m.`)}
function circleYZ(X,r,col,alpha){const pts=[];for(let a=0;a<=Math.PI*2+.01;a+=Math.PI/30)pts.push([X,r*Math.cos(a),r*Math.sin(a)]);path3(pts,col,1,alpha)}
function explain(title,body){const e=$("#sim3DExplainV15");if(e)e.innerHTML=`<strong>${title}</strong> · ${body}`}
function draw(){if(!c||!x)return;clear();const id=sim();if(id==="progressive")progressive();else if(id==="polarisation")polarisation();else if(id==="standing")standing();else if(id==="interference")interference();else if(id==="doubleSlit")doubleSlit();else if(id==="diffraction")diffraction();else if(id==="grating")grating();else if(id==="refraction")refraction();else if(id==="fibre")fibre();else progressive()}
function loop(ts){raf=requestAnimationFrame(loop);if(!active())return;if(ts-lastDraw<33)return;const dt=last?Math.min(.06,(ts-last)/1000):0;last=ts;lastDraw=ts;if(!paused())t+=dt*($("#slowMotion")?.classList.contains("primary")?.35:1);draw()}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",()=>{setTimeout(setup,220);raf=requestAnimationFrame(loop)});else{setTimeout(setup,220);raf=requestAnimationFrame(loop)}
})();