(()=>{
'use strict';
const $=(s,r=document)=>r.querySelector(s);
let c,ctx,W=900,H=520,DPR=1,yaw=-0.58,pitch=0.34,zoom=1,time=0,last=0,lastFrame=0,drag=false,px=0,py=0;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const current=()=>$('#simTabs .sim-tab.active')?.dataset.sim||'progressive';
const value=(k,f)=>{const e=$(`#simControls [data-sim-control='${k}']`);const n=Number(e?.value);return Number.isFinite(n)?n:f;};
const labActive=()=>$('#view-lab')?.classList.contains('active-view')&&!document.hidden;
const paused=()=>($('#simState')?.textContent||'').toLowerCase().includes('paused');
function setup(){
  const wrap=$('#view-lab .viewer-wrap'),old=$('#simCanvas');
  if(!wrap||!old||$('#simCanvas3DV16'))return;
  old.classList.add('legacy-sim-hidden-v15');wrap.classList.add('v15-3d-ready');
  c=document.createElement('canvas');c.id='simCanvas3DV16';c.className='waves-3d-v15';c.setAttribute('aria-label','Interactive rotatable 3D Waves simulation');wrap.insertBefore(c,wrap.firstChild);
  const help=document.createElement('div');help.className='sim-3d-help-v15';help.textContent='Drag to orbit · wheel to zoom · physics controls remain live';wrap.appendChild(help);
  const badge=document.createElement('div');badge.className='sim-3d-badge-v15';badge.textContent='Interactive 3D';wrap.appendChild(badge);
  const bar=document.createElement('div');bar.className='sim-3d-toolbar-v15';bar.innerHTML='<button data-v16cam="reset">Reset view</button><button data-v16cam="front">Front</button><button data-v16cam="top">Top</button><button data-v16cam="iso">Isometric</button>';wrap.appendChild(bar);
  bar.querySelectorAll('[data-v16cam]').forEach(b=>b.onclick=()=>camera(b.dataset.v16cam));
  const note=document.createElement('div');note.id='sim3DExplainV16';note.className='three-d-explain-v15';wrap.parentElement?.appendChild(note);
  ctx=c.getContext('2d');bind();resize();window.dispatchEvent(new Event('resize'));draw();
}
function bind(){
  c.addEventListener('pointerdown',e=>{drag=true;px=e.clientX;py=e.clientY;c.setPointerCapture?.(e.pointerId)});
  c.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-px,dy=e.clientY-py;px=e.clientX;py=e.clientY;yaw+=dx*0.008;pitch=clamp(pitch+dy*0.007,-1.25,1.25);draw()});
  c.addEventListener('pointerup',()=>drag=false);c.addEventListener('pointercancel',()=>drag=false);
  c.addEventListener('wheel',e=>{e.preventDefault();zoom=clamp(zoom*(e.deltaY>0?0.92:1.08),0.62,1.8);draw()},{passive:false});
  c.addEventListener('dblclick',()=>camera('reset'));
  document.addEventListener('input',e=>{if(e.target.matches?.('#simControls [data-sim-control]'))requestAnimationFrame(draw)});
  document.addEventListener('click',e=>{if(e.target.closest?.('[data-sim],#resetSim,#slowMotion,#playPause'))setTimeout(draw,35)});
  window.addEventListener('resize',resize);
}
function camera(k){if(k==='front'){yaw=0;pitch=0;zoom=1}else if(k==='top'){yaw=0;pitch=-1.2;zoom=.92}else if(k==='iso'){yaw=-.72;pitch=.5;zoom=1}else{yaw=-.58;pitch=.34;zoom=1}draw()}
function resize(){if(!c)return;const r=c.getBoundingClientRect();if(!r.width)return;DPR=Math.min(devicePixelRatio||1,1.6);W=r.width;H=r.height;c.width=Math.round(W*DPR);c.height=Math.round(H*DPR);ctx=c.getContext('2d');ctx.setTransform(DPR,0,0,DPR,0,0);draw()}
function rotate(p){let [X,Y,Z]=p;const cy=Math.cos(yaw),sy=Math.sin(yaw);let a=X*cy+Z*sy,b=-X*sy+Z*cy;const cp=Math.cos(pitch),sp=Math.sin(pitch);return[a,Y*cp-b*sp,Y*sp+b*cp]}
function project(p){const [X,Y,Z]=rotate(p),s=Math.min(W,H)*1.02*zoom/Math.max(3.8,8.2+Z);return{x:W/2+X*s,y:H/2-Y*s,s}}
function line(a,b,col='#67c7ff',lw=2,alpha=1,dash=[]){const A=project(a),B=project(b);ctx.save();ctx.globalAlpha=alpha;ctx.strokeStyle=col;ctx.lineWidth=lw;ctx.setLineDash(dash);ctx.beginPath();ctx.moveTo(A.x,A.y);ctx.lineTo(B.x,B.y);ctx.stroke();ctx.restore()}
function path(points,col='#67c7ff',lw=2,alpha=1){if(points.length<2)return;ctx.save();ctx.globalAlpha=alpha;ctx.strokeStyle=col;ctx.lineWidth=lw;ctx.beginPath();let q=project(points[0]);ctx.moveTo(q.x,q.y);for(let i=1;i<points.length;i++){q=project(points[i]);ctx.lineTo(q.x,q.y)}ctx.stroke();ctx.restore()}
function dot(p,r=5,col='#ffd56a',label=''){const q=project(p);ctx.save();ctx.fillStyle=col;ctx.shadowColor=col;ctx.shadowBlur=7;ctx.beginPath();ctx.arc(q.x,q.y,Math.max(2,r*q.s/70),0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;if(label){ctx.fillStyle='#dff5ff';ctx.font='700 11px system-ui';ctx.fillText(label,q.x+7,q.y-7)}ctx.restore()}
function poly(points,fill='rgba(103,199,255,.08)',stroke='rgba(103,199,255,.35)'){const p=points.map(project);ctx.save();ctx.fillStyle=fill;ctx.strokeStyle=stroke;ctx.lineWidth=1.1;ctx.beginPath();p.forEach((q,i)=>i?ctx.lineTo(q.x,q.y):ctx.moveTo(q.x,q.y));ctx.closePath();ctx.fill();ctx.stroke();ctx.restore()}
function label(txt,p,col='#dff5ff'){const q=project(p);ctx.fillStyle=col;ctx.font='700 11px system-ui';ctx.fillText(txt,q.x+6,q.y-5)}
function ring(cx,cz,r,y=0,col='#67c7ff',alpha=.25,start=0,end=Math.PI*2){const p=[];for(let a=start;a<=end+.001;a+=(end-start)/44)p.push([cx+r*Math.cos(a),y,cz+r*Math.sin(a)]);path(p,col,1.2,alpha)}
function yzRing(X,r,col='#477995',alpha=.35){const p=[];for(let a=0;a<=Math.PI*2+.01;a+=Math.PI/28)p.push([X,r*Math.cos(a),r*Math.sin(a)]);path(p,col,1,alpha)}
function clear(){ctx.setTransform(DPR,0,0,DPR,0,0);const g=ctx.createRadialGradient(W*.5,H*.35,20,W*.5,H*.5,Math.max(W,H)*.75);g.addColorStop(0,'#153b60');g.addColorStop(1,'#06111d');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);for(let i=-3;i<=3;i+=.5){line([-3,-1.75,i],[3,-1.75,i],'#27445e',.7,.34);line([i,-1.75,-3],[i,-1.75,3],'#27445e',.7,.34)}}
function explain(title,text){const e=$('#sim3DExplainV16');if(e)e.innerHTML=`<strong>${title}</strong> · ${text}`}
function progressive(){const A=.45+value('A',70)/130,L=clamp(value('lambda',220)/115,.8,3.2),phase=time*value('f',1.2)*2.4;for(const z of[-.72,0,.72]){const p=[];for(let X=-3;X<=3;X+=.06)p.push([X,A*Math.sin(X/L*Math.PI*2-phase),z]);path(p,z===0?'#67c7ff':'#8bbde0',z===0?3:1.2,z===0?1:.42)}for(let i=0;i<=12;i++){const X=-3+i*.5;dot([X,A*Math.sin(X/L*Math.PI*2-phase),0],4)}line([-2.7,1.55,-1],[2.45,1.55,-1],'#63d9a4',3,.85);label('energy / phase →',[.1,1.55,-1],'#9cf0ca');explain('Progressive wave in 3D','Particles oscillate locally while phase and energy propagate along the wave. Rotate the scene to separate the oscillation direction from the propagation direction.')}
function polarisation(){const transverse=value('mode',0)<.5,ang=value('angle',35)*Math.PI/180,phase=time*2.5;if(transverse){const p=[];for(let X=-3;X<=3;X+=.06)p.push([X,.8*Math.sin(X*3-phase),0]);path(p,'#67c7ff',3);for(let X=-2.7;X<=2.7;X+=.45){const E=.68*Math.sin(X*3-phase);line([X,0,0],[X,E,0],'#ffd56a',1.3,.65)}}else{for(let i=0;i<28;i++){const base=-3+i*6/27;dot([base+.16*Math.sin(base*5-phase),0,0],4,'#67c7ff')}}const X=1.35,R=1.25,u=[0,Math.cos(ang)*R,Math.sin(ang)*R],vv=[0,-Math.sin(ang)*R,Math.cos(ang)*R];poly([[X,u[1]+vv[1],u[2]+vv[2]],[X,u[1]-vv[1],u[2]-vv[2]],[X,-u[1]-vv[1],-u[2]-vv[2]],[X,-u[1]+vv[1],-u[2]+vv[2]]],'rgba(255,213,106,.07)','rgba(255,213,106,.65)');line([X,-u[1],-u[2]],[X,u[1],u[2]],'#ffd56a',4);label('analyser',[X,1.45,0]);explain('Polarisation in 3D',transverse?'The oscillation is perpendicular to propagation. Rotating the analyser changes how much of that transverse oscillation is selected.':'The particle displacement is parallel to propagation, showing a longitudinal wave with no transverse polarisation plane.')}
function standing(){const n=Math.round(value('n',2)),A=.35+value('A',80)/150,phase=Math.cos(time*3),p=[];for(let X=-3;X<=3;X+=.04)p.push([X,A*Math.sin(n*Math.PI*(X+3)/6)*phase,0]);path(p,'#67c7ff',3);for(let i=0;i<=n;i++){const X=-3+6*i/n;dot([X,0,0],5,'#ffbd66',i===0||i===n?'fixed':'node')}explain('Stationary wave in 3D',`The string contains ${n} half-wavelength section${n===1?'':'s'}. Nodes remain fixed while the antinodes oscillate.`)}
function interference(){const L=clamp(value('lambda',70)/60,.55,2),sep=clamp(value('sep',180)/105,.7,2.6),s1=[-1.8,0,-sep/2],s2=[-1.8,0,sep/2];dot(s1,7,'#63d9a4','S₁');dot(s2,7,'#9a86ff','S₂');for(const s of[s1,s2])for(let j=1;j<=5;j++)ring(s[0],s[2],((time*1.05+j*L)%5.2)+.1,0,s===s1?'#63d9a4':'#9a86ff',.16);const q=[-.5+value('px',.72)*4,.05,(value('py',.52)-.5)*5];dot(q,7,'#ffd56a','detector');line(s1,q,'#63d9a4',1,.5,[5,4]);line(s2,q,'#9a86ff',1,.5,[5,4]);explain('Two-source interference in 3D','Moving the detector changes the two path lengths. Their difference sets the phase difference and therefore whether the local interference is constructive or destructive.')}
function doubleSlit(){const sep=clamp(value('sMm',.35)*3.1,.5,2.1),D=value('D',2),lam=value('lambdaNm',600),bx=-1.5,screen=2.7;poly([[bx,-1.7,-2],[bx,1.7,-2],[bx,1.7,2],[bx,-1.7,2]],'rgba(120,145,165,.12)','rgba(160,180,198,.42)');const a=[bx,0,-sep/2],b=[bx,0,sep/2];dot(a,5,'#63d9a4','slit');dot(b,5,'#63d9a4','slit');poly([[screen,-1.7,-2.15],[screen,1.7,-2.15],[screen,1.7,2.15],[screen,-1.7,2.15]],'rgba(180,220,255,.04)','rgba(180,220,255,.35)');const spacing=clamp((lam/600)*(D/2)/Math.max(.15,value('sMm',.35))*.33,.16,.72);for(let k=-5;k<=5;k++){const z=k*spacing;if(Math.abs(z)>2)continue;line([screen,-1.25,z],[screen,1.25,z],k===0?'#fff4bd':'#67c7ff',k===0?5:3,Math.max(.18,1-Math.abs(k)*.12));line(a,[screen,0,z],'#63d9a4',.8,.15);line(b,[screen,0,z],'#9a86ff',.8,.15)}explain('Young double slit in 3D','The two slit paths to each screen position are visible. Changing wavelength, screen distance or slit separation changes the path-difference geometry and fringe spacing.')}
function diffraction(){const a=clamp(value('slitUm',40)/30,.35,2.6),lam=value('lambdaNm',600),bx=-1.3;poly([[bx,-1.8,-2],[bx,1.8,-2],[bx,1.8,-a/2],[bx,-1.8,-a/2]],'rgba(120,145,165,.14)','rgba(160,180,198,.4)');poly([[bx,-1.8,a/2],[bx,1.8,a/2],[bx,1.8,2],[bx,-1.8,2]],'rgba(120,145,165,.14)','rgba(160,180,198,.4)');const spread=clamp((lam/600)/(a/1.3)*.9,.25,1.35);for(let k=-6;k<=6;k++){const th=k/6*spread;line([bx,0,0],[3,0,Math.tan(th)*(3-bx)],k===0?'#dff5ff':'#67c7ff',k===0?2.5:1.2,Math.max(.12,1-Math.abs(k)*.1))}for(let r=.55;r<4.8;r+=.75)ring(bx,0,r,0,'#67c7ff',.14,-spread,spread);explain('Single-slit diffraction in 3D','The outgoing fan becomes wider when wavelength increases or slit width decreases, making the qualitative λ/aperture dependence visible.')}
function grating(){const N=value('linesMm',500)*1e3,lam=value('lambdaNm',600)*1e-9,d=1/N,bx=-1.4,max=Math.min(5,Math.floor(d/lam+1e-9));poly([[bx,-1.8,-2],[bx,1.8,-2],[bx,1.8,2],[bx,-1.8,2]],'rgba(120,145,165,.09)','rgba(160,180,198,.4)');for(let z=-1.75;z<=1.75;z+=.22)line([bx,-1.5,z],[bx,1.5,z],'#aabbd1',.75,.5);for(let n=-max;n<=max;n++){const s=n*lam/d;if(Math.abs(s)>1)continue;const th=Math.asin(s),z=Math.tan(th)*4.2;line([bx,0,0],[2.8,0,z],n===0?'#f1f7ff':'#67c7ff',n===0?2.4:2,.82);label(`n=${n}`,[2.55,.08,z])}explain('Diffraction grating in 3D',`The principal maxima leave at discrete angles. With these values the largest displayed order is |n|=${max}; higher orders require nλ≤d.`)}
function refraction(){const n1=value('n1',1.5),n2=value('n2',1),th1=value('theta',30)*Math.PI/180,s=n1*Math.sin(th1)/n2,tir=Math.abs(s)>1;poly([[-3,0,-3],[3,0,-3],[3,0,3],[-3,0,3]],'rgba(103,199,255,.055)','rgba(103,199,255,.25)');line([0,-2.2,0],[0,2.2,0],'#dfe9f1',1.2,.65,[5,4]);const L=2.8,inc=[-L*Math.sin(th1),L*Math.cos(th1),0];line(inc,[0,0,0],'#ffd56a',3);if(tir){line([0,0,0],[L*Math.sin(th1),L*Math.cos(th1),0],'#ffb36a',3);label('TIR',[1.2,1.5,0],'#ffd56a')}else{const th2=Math.asin(s);line([0,0,0],[L*Math.sin(th2),-L*Math.cos(th2),0],'#67c7ff',3);label('refracted',[1,-1.45,0],'#9fddff')}explain('Refraction and TIR in 3D',tir?'The ray is above the critical condition for this higher-to-lower index boundary, so the model shows total internal reflection.':'The transparent plane is the boundary and the dashed line is the normal. The ray direction follows Snell’s law while frequency remains unchanged.')}
function fibre(){const length=value('length',1000),modal=value('modal',3),spec=value('spectral',2),abs=value('absorption',.15),R=.72;for(let X=-3;X<=3;X+=.6)yzRing(X,R);for(let a=0;a<Math.PI*2;a+=Math.PI/6)line([-3,R*Math.cos(a),R*Math.sin(a)],[3,R*Math.cos(a),R*Math.sin(a)],'#477995',.9,.32);const modes=Math.max(1,Math.min(5,Math.round(modal/2)+1));for(let m=0;m<modes;m++){const p=[],amp=.16+m*.09,f=1.1+m*.42;for(let X=-2.9;X<=2.9;X+=.06)p.push([X,amp*Math.sin((X+3)*f*2+time*.8),amp*Math.cos((X+3)*f*2+time*.8)]);path(p,m%2?'#9a86ff':'#67c7ff',1.5,.66)}const X=-2.8+5.6*((time*.55)%1),loss=Math.pow(10,-abs*(length/1000)/10);dot([X,0,0],7+spec*.45,`rgba(255,213,106,${clamp(.25+loss*.75,.25,1)})`,'pulse');explain('Optical fibre in 3D',`The cylindrical core shows several guided paths. More path variety represents more modal dispersion; spectral width represents material dispersion; absorption reduces signal strength over the current ${Math.round(length)} m link.`)}
function draw(){if(!c||!ctx)return;clear();const id=current();({progressive,polarisation,standing,interference,doubleSlit,diffraction,grating,refraction,fibre}[id]||progressive)()}
function loop(ts){requestAnimationFrame(loop);if(!labActive())return;if(ts-lastFrame<33)return;const dt=last?Math.min(.06,(ts-last)/1000):0;last=ts;lastFrame=ts;if(!paused())time+=dt*($('#slowMotion')?.classList.contains('primary')?0.35:1);draw()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{setTimeout(setup,220);requestAnimationFrame(loop)});else{setTimeout(setup,220);requestAnimationFrame(loop)}
})();