(()=>{
'use strict';
const $=(s,r=document)=>r.querySelector(s);
let c,ctx,W=760,H=330,DPR=1,yaw=-.62,pitch=.38,zoom=1,time=0,last=0,lastFrame=0,drag=false,px=0,py=0;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const mode=()=>$('#studioTabs .studio-tab.active')?.dataset.studio||'measure';
const val=(k,f)=>{const e=$(`#studioBody [data-studio-control='${k}']`),n=Number(e?.value);return Number.isFinite(n)?n:f;};
function rot([X,Y,Z]){const cy=Math.cos(yaw),sy=Math.sin(yaw),x1=X*cy+Z*sy,z1=-X*sy+Z*cy,cp=Math.cos(pitch),sp=Math.sin(pitch);return[x1,Y*cp-z1*sp,Y*sp+z1*cp]}
function P(p){const [X,Y,Z]=rot(p),s=Math.min(W,H)*1.12*zoom/Math.max(3.9,8.4+Z);return{x:W/2+X*s,y:H/2-Y*s,s}}
function line(a,b,col='#67c7ff',lw=2,alpha=1,dash=[]){const A=P(a),B=P(b);ctx.save();ctx.globalAlpha=alpha;ctx.strokeStyle=col;ctx.lineWidth=lw;ctx.setLineDash(dash);ctx.beginPath();ctx.moveTo(A.x,A.y);ctx.lineTo(B.x,B.y);ctx.stroke();ctx.restore()}
function path(points,col='#67c7ff',lw=2,alpha=1){if(points.length<2)return;ctx.save();ctx.globalAlpha=alpha;ctx.strokeStyle=col;ctx.lineWidth=lw;ctx.beginPath();let q=P(points[0]);ctx.moveTo(q.x,q.y);for(let i=1;i<points.length;i++){q=P(points[i]);ctx.lineTo(q.x,q.y)}ctx.stroke();ctx.restore()}
function dot(p,r=5,col='#ffd56a',txt=''){const q=P(p);ctx.fillStyle=col;ctx.beginPath();ctx.arc(q.x,q.y,Math.max(2,r*q.s/70),0,Math.PI*2);ctx.fill();if(txt){ctx.fillStyle='#eaf6ff';ctx.font='700 10px system-ui';ctx.fillText(txt,q.x+6,q.y-6)}}
function poly(points,fill='rgba(103,199,255,.07)',stroke='rgba(103,199,255,.35)'){const ps=points.map(P);ctx.save();ctx.fillStyle=fill;ctx.strokeStyle=stroke;ctx.beginPath();ps.forEach((q,i)=>i?ctx.lineTo(q.x,q.y):ctx.moveTo(q.x,q.y));ctx.closePath();ctx.fill();ctx.stroke();ctx.restore()}
function ring(cx,cz,r,y=0,col='#67c7ff',alpha=.22){const p=[];for(let a=0;a<=Math.PI*2+.01;a+=Math.PI/28)p.push([cx+r*Math.cos(a),y,cz+r*Math.sin(a)]);path(p,col,1.1,alpha)}
function yzRing(X,r,col='#477995',alpha=.35){const p=[];for(let a=0;a<=Math.PI*2+.01;a+=Math.PI/28)p.push([X,r*Math.cos(a),r*Math.sin(a)]);path(p,col,1,alpha)}
function text(s,p,col='#dff5ff'){const q=P(p);ctx.fillStyle=col;ctx.font='700 10px system-ui';ctx.fillText(s,q.x+5,q.y-4)}
function clear(){ctx.setTransform(DPR,0,0,DPR,0,0);const g=ctx.createRadialGradient(W*.5,H*.35,10,W*.5,H*.55,Math.max(W,H)*.7);g.addColorStop(0,'#153b60');g.addColorStop(1,'#06111d');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);for(let i=-3;i<=3;i+=.75){line([-3,-1.65,i],[3,-1.65,i],'#29445d',.7,.28);line([i,-1.65,-3],[i,-1.65,3],'#29445d',.7,.28)}}
function caption(title,body){const e=$('#studio3DCaptionV18');if(e&&e.dataset.key!==title+body){e.dataset.key=title+body;e.innerHTML=`<strong>${title}</strong> · ${body}`}}
function measure(){const A=.4+val('A',55)/120,L=clamp(val('lambda',210)/105,.9,3.1),f=val('f',2),ph=time*f*2;const p=[];for(let X=-3;X<=3;X+=.05)p.push([X,A*Math.sin(X/L*Math.PI*2-ph),0]);path(p,'#67c7ff',3);for(let i=0;i<15;i++){const X=-2.8+i*.4;dot([X,A*Math.sin(X/L*Math.PI*2-ph),0],3.6,'#ffd56a')}for(const [X,name] of[[-1.2,'A'],[1.1,'B']]){poly([[X,-1.25,-1],[X,1.25,-1],[X,1.25,1],[X,-1.25,1]],'rgba(255,213,106,.025)','rgba(255,213,106,.38)');text(name,[X,1.35,0],'#ffd56a')}caption('3D wave measurement','The original panel remains the precision ruler/oscilloscope surface. This linked 3D view shows the wave and two measurement planes in spatial perspective.')}
function interference(){const L=clamp(val('lambda',70)/58,.55,2),sep=clamp(val('sep',180)/105,.75,2.6),a=[-1.8,0,-sep/2],b=[-1.8,0,sep/2];dot(a,7,'#63d9a4','S₁');dot(b,7,'#9a86ff','S₂');for(const s of[a,b])for(let j=0;j<5;j++)ring(s[0],s[2],((time*1.05+j*L)%4.8)+.2,0,s===a?'#63d9a4':'#9a86ff',.18);const q=[1.8,.05,.45];dot(q,7,'#ffd56a','P');line(a,q,'#63d9a4',1,.55,[5,4]);line(b,q,'#9a86ff',1,.55,[5,4]);caption('3D two-source geometry','Use the draggable detector on the measurement surface above. This 3D view makes the two source-to-point paths and expanding coherent wavefronts easier to visualise.')}
function young(){const sep=clamp(val('s',.35)*3.1,.5,2.1),D=val('D',2),lam=val('lambda',600),plate=-1.5,screen=2.65;poly([[plate,-1.65,-2],[plate,1.65,-2],[plate,1.65,2],[plate,-1.65,2]],'rgba(140,160,180,.11)','rgba(180,195,210,.42)');const s1=[plate,0,-sep/2],s2=[plate,0,sep/2];dot(s1,5,'#63d9a4','slit');dot(s2,5,'#63d9a4','slit');poly([[screen,-1.65,-2.1],[screen,1.65,-2.1],[screen,1.65,2.1],[screen,-1.65,2.1]],'rgba(180,220,255,.04)','rgba(180,220,255,.34)');const spacing=clamp((lam/600)*(D/2)/Math.max(.15,val('s',.35))*.33,.16,.72);for(let k=-4;k<=4;k++){const z=k*spacing;if(Math.abs(z)>2)continue;line([screen,-1.15,z],[screen,1.15,z],k===0?'#fff3bc':'#67c7ff',k===0?4.5:2.5,Math.max(.2,1-Math.abs(k)*.14));line(s1,[screen,0,z],'#63d9a4',.8,.13);line(s2,[screen,0,z],'#9a86ff',.8,.13)}caption('3D Young apparatus','The slit plate, screen and paired optical paths are shown in depth. Keep using the cursor above for quantitative fringe measurements.')}
function diffraction(){const a=clamp(val('a',35)/28,.35,2.5),lam=val('lambda',600),plate=-1.25;poly([[plate,-1.7,-2],[plate,1.7,-2],[plate,1.7,-a/2],[plate,-1.7,-a/2]],'rgba(130,150,170,.12)','rgba(180,195,210,.4)');poly([[plate,-1.7,a/2],[plate,1.7,a/2],[plate,1.7,2],[plate,-1.7,2]],'rgba(130,150,170,.12)','rgba(180,195,210,.4)');const spread=clamp((lam/600)/(a/1.25)*.85,.22,1.3);for(let k=-6;k<=6;k++){const th=k/6*spread;line([plate,0,0],[3,0,Math.tan(th)*(3-plate)],k===0?'#eaf6ff':'#67c7ff',k===0?2.5:1.2,Math.max(.13,1-Math.abs(k)*.11))}caption('3D single-slit apparatus','The outgoing angular fan widens when λ/a increases. The intensity-profile graph above remains the quantitative measurement view.')}
function spectrometer(){const lines=val('lines',600)*1e3,d=1/lines,th=val('telescope',20)*Math.PI/180;poly([[-1.15,-1.55,-1.8],[-1.15,1.55,-1.8],[-1.15,1.55,1.8],[-1.15,-1.55,1.8]],'rgba(140,160,180,.09)','rgba(180,195,210,.4)');for(let z=-1.55;z<=1.55;z+=.19)line([-1.15,-1.35,z],[-1.15,1.35,z],'#aabbd1',.65,.5);const L=3.4,end=[-1.15+L*Math.cos(th),0,L*Math.sin(th)];line([-1.15,0,0],end,'#ffd56a',5,.9);dot(end,7,'#ffd56a','telescope');const source=$('#spectrumSource')?.value||'hydrogen';const sets={hydrogen:[410,434,486,656],mercury:[405,436,546,577],unknown:[447,502,588,668]};for(const nm of sets[source]){const s=nm*1e-9/d;if(s<=1){const a=Math.asin(s);line([-1.15,0,0],[-1.15+3*Math.cos(a),0,3*Math.sin(a)],'#67c7ff',1.4,.45)}}caption('3D grating spectrometer','The yellow arm is the movable telescope. The other beams show first-order spectral directions generated by the grating spacing and selected source.')}
function fibre(){const len=val('length',1200),modes=Math.round(val('modes',5)),spec=val('spectral',3),abs=val('absorption',.18),R=.72;for(let X=-3;X<=3;X+=.6)yzRing(X,R);for(let a=0;a<Math.PI*2;a+=Math.PI/6)line([-3,R*Math.cos(a),R*Math.sin(a)],[3,R*Math.cos(a),R*Math.sin(a)],'#477995',.9,.32);const count=Math.min(5,Math.max(1,modes));for(let m=0;m<count;m++){const p=[],amp=.14+m*.085,f=1+m*.38;for(let X=-2.9;X<=2.9;X+=.06)p.push([X,amp*Math.sin((X+3)*f*2+time*.7),amp*Math.cos((X+3)*f*2+time*.7)]);path(p,m%2?'#9a86ff':'#67c7ff',1.4,.64)}const loss=Math.pow(10,-abs*(len/1000)/10),X=-2.8+5.6*((time*.5)%1);dot([X,0,0],7+spec*.35,`rgba(255,213,106,${clamp(.25+loss*.75,.25,1)})`,'pulse');caption('3D fibre apparatus','The cylindrical core and alternative guided paths are shown in depth. The pulse analyser below remains linked to dispersion and attenuation controls.')}
function resonance(){const L=val('L',1.2),T=val('T',18),mu=val('mu',.005),drive=val('drive',50),damping=val('damping',.8),speed=Math.sqrt(T/mu),f1=speed/(2*L),n=Math.max(1,Math.min(8,Math.round(drive/f1))),fn=n*f1,det=Math.abs(drive-fn),amp=.25+clamp(1/Math.sqrt(det*det+damping*damping),0,1.2)*.7;line([-3,0,0],[3,0,0],'#7890aa',2,.6);const p=[];for(let X=-3;X<=3;X+=.04)p.push([X,amp*Math.sin(n*Math.PI*(X+3)/6)*Math.cos(time*drive*.14),0]);path(p,'#67c7ff',3);for(let i=0;i<=n;i++)dot([-3+6*i/n,0,0],4,'#ffbd66',i===0||i===n?'support':'node');caption('3D resonance apparatus',`The driven string is shown near harmonic n=${n}; resonance strengthens as the drive frequency approaches ${fn.toFixed(1)} Hz.`)}
function draw(){if(!ctx||!c)return;clear();const id=mode();({measure,interference,young,diffraction,spectrometer,fibre,resonance}[id]||measure)()}
function camera(k){if(k==='front'){yaw=0;pitch=0;zoom=1}else if(k==='top'){yaw=0;pitch=-1.2;zoom=.92}else{yaw=-.62;pitch=.38;zoom=1}draw()}
function bind(){c.addEventListener('pointerdown',e=>{drag=true;px=e.clientX;py=e.clientY;c.setPointerCapture?.(e.pointerId)});c.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-px,dy=e.clientY-py;px=e.clientX;py=e.clientY;yaw+=dx*.008;pitch=clamp(pitch+dy*.007,-1.25,1.25);draw()});c.addEventListener('pointerup',()=>drag=false);c.addEventListener('pointercancel',()=>drag=false);c.addEventListener('wheel',e=>{e.preventDefault();zoom=clamp(zoom*(e.deltaY>0?.92:1.08),.62,1.8);draw()},{passive:false});document.addEventListener('input',e=>{if(e.target.closest?.('#studioBody'))requestAnimationFrame(draw)});document.addEventListener('change',e=>{if(e.target.closest?.('#studioBody'))requestAnimationFrame(draw)})}
function resize(){if(!c)return;const r=c.getBoundingClientRect();if(!r.width)return;DPR=Math.min(devicePixelRatio||1,1.6);W=r.width;H=r.height;c.width=Math.round(W*DPR);c.height=Math.round(H*DPR);ctx=c.getContext('2d');ctx.setTransform(DPR,0,0,DPR,0,0);draw()}
function ensure(){const body=$('#studioBody'),stage=body?.querySelector('.studio-stage'),id=mode();if(!body||!stage||id==='investigations'||body.querySelector('#studio3DV18'))return;const box=document.createElement('section');box.id='studio3DV18';box.className='studio-3d-v18';box.innerHTML='<div class="studio-3d-head-v18"><div><span class="eyebrow">Linked spatial model</span><h4>3D apparatus view</h4><p class="muted small">Rotate the apparatus, then use the measurement surface above for exact readings.</p></div><span class="mini-badge good">3D</span></div><div class="studio-3d-view-v18"><canvas id="studio3DCanvasV18" class="studio-3d-canvas-v18"></canvas><div class="studio-3d-controls-v18"><button data-studio3dcam="reset">Reset</button><button data-studio3dcam="front">Front</button><button data-studio3dcam="top">Top</button></div></div><div class="studio-3d-caption-v18" id="studio3DCaptionV18"></div>';stage.appendChild(box);c=$('#studio3DCanvasV18');ctx=c.getContext('2d');bind();box.querySelectorAll('[data-studio3dcam]').forEach(b=>b.onclick=()=>camera(b.dataset.studio3dcam));resize()}
let queued=false;function schedule(){if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;ensure()})}
const body=$('#studioBody');if(body)new MutationObserver(schedule).observe(body,{childList:true,subtree:false});window.addEventListener('resize',resize);
function loop(ts){requestAnimationFrame(loop);if(!$('#view-studio')?.classList.contains('active-view')||document.hidden||!$('#studio3DV18'))return;if(ts-lastFrame<33)return;const dt=last?Math.min(.06,(ts-last)/1000):0;last=ts;lastFrame=ts;time+=dt;draw()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{setTimeout(ensure,400);requestAnimationFrame(loop)});else{setTimeout(ensure,400);requestAnimationFrame(loop)}
})();